[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dem4cli"
version = "0.1.0"
description = "Demography-climate lifetime exposure tools"
authors = [
  {name = "Rosa Pietroiusti", email = "rosa.pietroiusti@vub.be"},
  {name = "Amaury Laridon", email = "amaury.laridon@vub.be"},
  {name = "Quentin Lejeune", email = "quentin.lejeune@vub.be"},
]
requires-python = ">=3.7"
dependencies = [
  "numpy",
  "xarray",
  "pandas",
  "geopandas",
  "regionmask",
  "shapely",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["dem4cli"]
